### ISSUE TITLE
Request for file removal: AGaramondPro Regular.otf

### ISSUE THREAD

**Issue by miguelsousa** [vtron/Cinder-Text#1]
When using http://www.getthefont.com/, I found your font file [AGaramondPro Regular.otf](http://github.com/vtron/Cinder-Typography/blob/a5508b48456741ff82f77a5c02a02ec52b0dca9c/_testing/FreetypeBasicLoading/assets/AGaramondPro%20Regular.otf), uploaded in this repository. I believe that this file was uploaded here by mistake, because its license does not allow distribution through a public website.

I would like to kindly ask you to remove this font file from the repository.

Kind regards,

**Comment by vtron** [comment]
Noted, removed.

Could you by chance recommend a font containing ligatures that I can use for testing?

**Comment by miguelsousa** [comment]
[Source Serif Pro](https://github.com/adobe-fonts/source-serif-pro/releases/latest)

**Comment by vtron** [comment]
Thanks!
