### ISSUE TITLE
Font-scaling issue on higher DPI screen

### ISSUE THREAD

**Issue by mikeedwards** [vtron/Cinder-Text#6]
Prior to installing the latest version of Cinder with [support for high-density displays](https://github.com/cinder/Cinder/pull/1934) we had a bug that required us to scale our font sizes down by about 2/3 to 1/2 to get it to look like the proper size (e.g. 120 became 80 to 60). _After_ updating to the latest version of Cinder, we instead had to scale to about 1/3 to 1/4 the size to get it to fit (e.g. 120 became 40 to 30). It seems like the scaling factor in Cinder-Text might be inverted, i.e. something that should be getting divided post-Cinder-update is instead getting multiplied, resulting in ~4x font sizes (instead of the ~2x font sizes that were the original problem.)

**Comment by vtron** [comment]
Defaulting to 96 dpi as the font scalar resolution value in Freetype. Will need to implement High-DPI rendering at the renderer level when retrieving glyphs
